### ISSUE TITLE
audio-sldeshow adds extra blank slides to slideshow

### ISSUE THREAD

**Issue by matbury** [rajgoel/reveal.js#9]
Hi Raj,

Firstly, thanks for developing a great plugin for reveal.js. It's incredibly useful :)

I'm trying it out for the first time so I may be missing something but here's what I'm doing (with HTML brackets removed):
<pre class="source">
 section
    h3 Chapter One /h3 
 /section 

 section 
     p class="fragment" data-audio-src="_presentation_/matbury/canterville_ghost/audio/01.mp3" When Hyram B. Otis, the American businessman, bought the house called Canterville Chase, people told him that he was doing a very dangerous thing. /p 
     p class="fragment" data-audio-src="_presentation_/matbury/canterville_ghost/audio/02.mp3" Everybody knew that there was a ghost in the house. /p 
 /section 

 section 
     p class="fragment" data-audio-src="_presentation_/matbury/canterville_ghost/audio/03.mp3" Lord Canterville himself told Mr. Otis all about it. /p 
     p class="fragment" data-audio-src="_presentation_/matbury/canterville_ghost/audio/04.mp3"  "We don't like to live in the house ourselves," He said. /p 
 /section 
</pre>
etc...

What happens is that in between each slide where's there's at least one node with a data-audio-src attribute, it inserts an additional 5 second blank slide before the next one. If I change the section nodes to  section data-audio-text="" , the additional blanks slides are no longer inserted.

Strange behaviour. Is this a bug or am I doing something wrong?

Thanks in advance :)

**Comment by rajgoel** [comment]
Hi,
the audioslideshow-plugin does not insert a slide. What happens is that the first fragment is shown **after** the "initial" slide and the sound for the "initial" slide is played before the first fragment. This is intended behaviour because there are cases where you want to show some content and play the respective audio **before** showing the first fragment. In your case a blank 5 seconds audio is played because no audio file is found. 

The following slide would be similar to yours, but without the need for your workaround (however, the slide would not start as a blank slide without content)

```
 <section data-audio-src="_presentation_/matbury/canterville_ghost/audio/01.mp3">
    <p>When Hyram B. Otis, the American businessman, bought the house called Canterville Chase, people told him that he was doing a very dangerous thing. </p> 
    <p class="fragment" data-audio-src="_presentation_/matbury/canterville_ghost/audio/02.mp3"> Everybody knew that there was a ghost in the house. </p> 
 </section> 
```

Hope this clarifies the behaviour of the plugin.

**Comment by matbury** [comment]
Yes, that makes sense. I can work with that. Thanks! :)
